name: Deploy to Render

on:
  push:
    branches:
      - main
    # Only deploy when code (not configuration files) changes
    paths:
      - "**/*.py"
      - "**/*.html"
      - "**/*.css"
      - "**/*.js"
      - "**/templates/**"
      - "**/static/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Cache Python dependencies
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      # Step 4: Install Dependencies
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Run Migrations
      - name: Run Migrations
        run: python manage.py migrate

      # Step 6: Collect Static Files
      - name: Collect Static Files
        run: python manage.py collectstatic --noinput

      # Step 7: Deploy to Render
      - name: Deploy to Render
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -d ""
