name: Deploy to Render

on:
  push:
    branches:
      - main
    # Only deploy when code (not configuration files) changes
    paths:
      - "**/*.py"
      - "**/*.html"
      - "**/*.css"
      - "**/*.js"
      - "**/templates/**"
      - "**/static/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Migrations
        run: python manage.py migrate

      - name: Collect Static Files
        run: python manage.py collectstatic --noinput

      - name: Deploy to Render
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -d ""
